WindowManager:
    LoginWindow:
    LoadingWindow:
    LoadingtableWindow:
    MaketableWindow:
    MainWindow:
    WinWindow:
    LoseWindow:

###################################################################################### Lose Window
<LoseWindow>
    name: "lose"

    canvas:
        Color: 
            rgba: (1, 1, 1, 1)
        Rectangle: 
            source:'asset/bingo_lose.jpg'
            size: root.width, root.height
