WindowManager:
    LoginWindow:
    LoadingWindow:
    LoadingtableWindow:
    MaketableWindow:
    MainWindow:
    WinWindow:
    LoseWindow:

######################################################################################  Win Window
<WinWindow>
    name: "win"

    canvas:
        Color: 
            rgba: (1, 1, 1, 1)
        Rectangle: 
            source:'asset/bingo_win.jpg'
            size: root.width, root.height
